### ISSUE TITLE
je ne fait que passer xD

### ISSUE THREAD

**Issue by galyfray** [simlefebvre/ProjetAP4B#1]
https://github.com/simlefebvre/ProjetAP4B/blob/01b6e6b76c89647ce1ca8b71fb5e793e8ee5a403/src/Model/DataBase/BaseDeDonee.java#L15

les élément static sont par convention en java en full maj c'est pris en compte dans la notation de mémoire :)

**Comment by galyfray** [comment]
petite question mais il y as une vrai raison derrière le fait que les admin le personnel et les utilisateur soit des classe différente et que le type soit pas représenter par un bête champ ?

**Comment by simlefebvre** [comment]
tkt c'est un copier coller du cours

**Comment by galyfray** [comment]
AH ! xD
